language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - pip install pytest coveralls pytest-cov==2.6 matplotlib
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov tatapov --cov-report term-missing

after_success:
  - coveralls
