language: python
python:
  - "3.9"
# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip --version
  - pip install --upgrade pytest coveralls pytest-cov
  - pip install matplotlib
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov tatapov --cov-report term-missing

after_success:
  - coveralls
